version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000
  - package-ecosystem: gomod
    directory: "/go"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000
  - package-ecosystem: pip
    directory: "/grpc_py"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000
  - package-ecosystem: pip
    directory: "/tests/e2e"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000
