version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Asia/Tokyo"
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Asia/Tokyo"
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Asia/Tokyo"
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
  - package-ecosystem: gomod
    directory: "/go"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Asia/Tokyo"
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
  - package-ecosystem: pip
    directory: "/grpc_py"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Asia/Tokyo"
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
  - package-ecosystem: cargo
    directory: "/id_generator"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Asia/Tokyo"
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
  - package-ecosystem: pip
    directory: "/tests/e2e"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Asia/Tokyo"
    groups:
      patch:
        update-types:
          - "patch"
      minor:
        update-types:
          - "minor"
