{
  "updates": [
    {
      "directory": "/",
      "package-ecosystem": "docker",
      "schedule": {
        "interval": "daily"
      }
    },
    {
      "directory": "/api_v2",
      "groups": {
        "minor": {
          "update-types": [
            "minor"
          ]
        },
        "patch": {
          "update-types": [
            "patch"
          ]
        }
      },
      "package-ecosystem": "cargo",
      "schedule": {
        "interval": "daily"
      }
    },
    {
      "directory": "/id_generator",
      "groups": {
        "minor": {
          "update-types": [
            "minor"
          ]
        },
        "patch": {
          "update-types": [
            "patch"
          ]
        }
      },
      "package-ecosystem": "cargo",
      "schedule": {
        "interval": "daily"
      }
    },
    {
      "directory": "/",
      "groups": {
        "minor": {
          "update-types": [
            "minor"
          ]
        },
        "patch": {
          "update-types": [
            "patch"
          ]
        }
      },
      "package-ecosystem": "github-actions",
      "schedule": {
        "interval": "daily"
      }
    },
    {
      "directory": "/",
      "groups": {
        "minor": {
          "update-types": [
            "minor"
          ]
        },
        "patch": {
          "update-types": [
            "patch"
          ]
        }
      },
      "package-ecosystem": "npm",
      "schedule": {
        "interval": "daily"
      }
    },
    {
      "directory": "/client",
      "groups": {
        "minor": {
          "update-types": [
            "minor"
          ]
        },
        "patch": {
          "update-types": [
            "patch"
          ]
        }
      },
      "package-ecosystem": "npm",
      "schedule": {
        "interval": "daily"
      }
    },
    {
      "directory": "/",
      "groups": {
        "minor": {
          "update-types": [
            "minor"
          ]
        },
        "patch": {
          "update-types": [
            "patch"
          ]
        }
      },
      "package-ecosystem": "pip",
      "schedule": {
        "interval": "daily"
      }
    },
    {
      "directory": "/tests/e2e",
      "groups": {
        "minor": {
          "update-types": [
            "minor"
          ]
        },
        "patch": {
          "update-types": [
            "patch"
          ]
        }
      },
      "package-ecosystem": "pip",
      "schedule": {
        "interval": "daily"
      }
    }
  ],
  "version": 2
}
