language: python
services:
  - docker
os:
  - linux
python:
  - "3.6"
notifications:
    email: false
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
script:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - DOCKER_BUILDKIT=1 docker build -q -t kshramt/evidence_based_scheduling:latest .
  - docker run -d --name server --rm -p 5000:5000 -v "$PWD":/app/data kshramt/evidence_based_scheduling
  - curl http://localhost:5000
  - docker kill server
