services:
  devcontainer:
    depends_on:
      docker_sock:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
      target: devcontainer
      args:
        devcontainer_user: ${USER:?}
        host_home: ${HOME:?}
    cap_add:
      - SYS_PTRACE
    init: true
    # network_mode: host
    security_opt:
      - seccomp:unconfined
    environment:
      HOST_HOME: ${HOME:?}
      DOCKER_HOST: tcp://docker_sock:2375
    volumes:
      - cache:/home/${USER:?}/.cache
      - type: bind
        source: /
        target: /h
      - type: bind
        source: ${PWD}
        target: ${PWD}
    command: sleep infinity
  docker_sock:
    image: alpine/socat:1.7.4.4
    init: true
    # network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${MY_DOCKER_HOST_PATH:-/var/run/docker.sock}
        target: /var/run/docker.sock
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
volumes:
  cache:
