services:
  api_v1:
    build:
      context: .
      target: prod_api_v1
    ports:
      - "${API_V1_PORT:-50051}:50051"
  api_v2:
    build:
      context: .
      target: prod_api_v2
    ports:
      - "${API_V2_PORT:-8585}:8080"
  nginx:
    build:
      context: .
      target: prod_nginx
  envoy:
    build:
      context: .
      target: prod_envoy
  postgres:
    build:
      context: .
      target: prod_postgres
  postgres_migration:
    build:
      context: .
      target: prod_postgres_migration
  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
    - "${ADMINER_PORT:-9090}:8080"
