services:
  api_v1:
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      MY_DB_URI: user=app host=postgres dbname=postgres password=${_POSTGRES_APP_USER_PASSWORD?}
  nginx:
    restart: always
  envoy:
    restart: always
    depends_on:
      - api_v1
      - nginx
    ports:
      - "${ENVOY_HTTP_PORT:-8080}:8080"
      - "${ENVOY_GRPC_PORT:-50051}:50051"
  postgres:
    command:
      - -c
      - logging_collector=on
      - -c
      - log_line_prefix='[%t]%u %d %p[%l]'
      - -c
      - log_min_duration_statement=5000
    restart: always
    environment:
      LANG: C.UTF-8
      POSTGRES_PASSWORD: ${_POSTGRES_PASSWORD?}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ${MY_HOST_PGDATA:-./pgdata}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
# volumes:
#   pgdata:
