services:
  api_v1:
    build:
      context: .
      target: prod_api_v1
    ports:
      - "${API_V1_PORT:-8585}:50051"
  nginx:
    build:
      context: .
      target: prod_nginx
  envoy:
    build:
      context: .
      target: prod_envoy
  postgres:
    build:
      context: .
      target: prod_postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - postgres
    ports:
    - "${ADMINER_PORT:-9090}:8080"
