services:
  api:
    restart: always
    volumes:
      - ${DOCKER_API_DATA_DIR:-./data}:/data
  nginx:
    restart: always
  envoy:
    restart: always
    depends_on:
      - api
      - nginx
    ports:
      - "8080:8080"
