services:
  api:
    restart: always
    volumes:
      - ${_DOCKER_API_DATA_DIR:-./data}:/data
  nginx:
    restart: always
  envoy:
    restart: always
    depends_on:
      - api
      - nginx
      - postgres
    ports:
      - "8080:8080"
  postgres:
    restart: always
    environment:
      LANG: C.utf8
      POSTGRES_PASSWORD: ${_POSTGRES_PASSWORD?}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
