services:
  api:
    build: 
      context: .
      target: prod_api
    environment:
      - USE_LITESTREAM=no
  nginx:
    build: 
      context: .
      target: prod_nginx
  envoy:
    build:
      context: .
      target: prod_envoy
  postgres:
    build:
      context: .
      target: prod_postgres
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - postgres
    ports:
    - 9090:8080
