packages:
  - "client"
catalog:
  "@emotion/react": ^11.11.3
  "@fontsource/material-icons": ^5.0.11
  "@kshramt/fast-json-patch": ^3.1.2
  "@kshramt/runtime-type-validator": ^0.13.0
  "@kshramt/sequence-comparisons": ^0.5.0
  "@mantine/core": ^7.3.2
  "@mantine/dates": ^7.3.2
  "@mantine/form": ^7.3.2
  "@mantine/hooks": ^7.3.2
  "@mantine/notifications": ^7.3.2
  "@playwright/experimental-ct-react": ^1.40.1
  "@reduxjs/toolkit": ^2.0.1
  "@types/node": ^20.10.6
  "@types/react": npm:types-react@rc
  "@types/react-dom": npm:types-react-dom@rc
  "@types/react-window": ^1.8.8
  "@typescript-eslint/eslint-plugin": ^6.16.0
  "@typescript-eslint/parser": ^6.16.0
  "@vitejs/plugin-react": ^4.3.1
  "@vitest/browser": ^1.1.0
  "@vitest/coverage-istanbul": ^1.1.0
  "@vitest/ui": ^1.1.0
  "@zodios/core": ^10.9.6
  autoprefixer: ^10.4.21
  babel-plugin-react-compiler: 0.0.0-experimental-334f00b-20240725
  dayjs: ^1.11.13
  eslint: ^8.56.0
  eslint-import-resolver-typescript: ^3.6.1
  "eslint-plugin-import": ^2.29.1
  "eslint-plugin-jsx-a11y": ^6.8.0
  "eslint-plugin-react": ^7.33.2
  "eslint-plugin-react-compiler": 0.0.0-experimental-9ed098e-20240725
  "eslint-plugin-react-hooks": ^4.6.0
  "eslint-plugin-testing-library": ^6.2.0
  idb: ^8.0.3
  immer: ^10.0.3
  jotai: ^2.6.1
  openapi-zod-client: ^1.15.0
  playwright: ^1.40.1
  postcss: ^8.4.32
  prettier: ^3.1.1
  react: ^19.0.0-rc-14a4699f-20240725
  "react-dnd": ^16.0.1
  "react-dnd-html5-backend": ^16.0.1
  "react-dom": ^19.0.0-rc-14a4699f-20240725
  "react-redux": ^9.0.4
  "react-virtuoso": ^4.6.2
  "react-window": ^1.8.11
  tailwindcss: ^3.4.0
  "ts-prune": ^0.10.3
  typescript: ^5.5.4
  vite: ^5.0.10
  "vite-plugin-pwa": ^0.17.4
  vitest: ^1.1.0
  workbox-core: ^7.0.0
  "workbox-expiration": ^7.0.0
  "workbox-precaching": ^7.0.0
  "workbox-routing": ^7.0.0
  "workbox-strategies": ^7.0.0
  zod: ^3.22.4
