/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Etag
 */
export interface Etag {
}

export function EtagFromJSON(json: any): Etag {
    return EtagFromJSONTyped(json, false);
}

export function EtagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Etag {
    return json;
}

export function EtagToJSON(value?: Etag | null): any {
    return value;
}

