/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface HBEmptyHeaderUser
 */
export interface HBEmptyHeaderUser {
    /**
     * 
     * @type {object}
     * @memberof HBEmptyHeaderUser
     */
    header: object;
    /**
     * 
     * @type {User}
     * @memberof HBEmptyHeaderUser
     */
    body: User;
}

export function HBEmptyHeaderUserFromJSON(json: any): HBEmptyHeaderUser {
    return HBEmptyHeaderUserFromJSONTyped(json, false);
}

export function HBEmptyHeaderUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBEmptyHeaderUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': json['header'],
        'body': UserFromJSON(json['body']),
    };
}

export function HBEmptyHeaderUserToJSON(value?: HBEmptyHeaderUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': value.header,
        'body': UserToJSON(value.body),
    };
}

