/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Data,
    DataFromJSON,
    DataFromJSONTyped,
    DataToJSON,
} from './Data';
import {
    EtagHeader,
    EtagHeaderFromJSON,
    EtagHeaderFromJSONTyped,
    EtagHeaderToJSON,
} from './EtagHeader';

/**
 * 
 * @export
 * @interface HBEtagHeaderData
 */
export interface HBEtagHeaderData {
    /**
     * 
     * @type {EtagHeader}
     * @memberof HBEtagHeaderData
     */
    header: EtagHeader;
    /**
     * 
     * @type {Data}
     * @memberof HBEtagHeaderData
     */
    body: Data;
}

export function HBEtagHeaderDataFromJSON(json: any): HBEtagHeaderData {
    return HBEtagHeaderDataFromJSONTyped(json, false);
}

export function HBEtagHeaderDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBEtagHeaderData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': EtagHeaderFromJSON(json['header']),
        'body': DataFromJSON(json['body']),
    };
}

export function HBEtagHeaderDataToJSON(value?: HBEtagHeaderData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': EtagHeaderToJSON(value.header),
        'body': DataToJSON(value.body),
    };
}

