/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Patch,
    PatchFromJSON,
    PatchFromJSONTyped,
    PatchToJSON,
} from './Patch';
import {
    PathHeader,
    PathHeaderFromJSON,
    PathHeaderFromJSONTyped,
    PathHeaderToJSON,
} from './PathHeader';

/**
 * 
 * @export
 * @interface HBPathHeaderPatch
 */
export interface HBPathHeaderPatch {
    /**
     * 
     * @type {PathHeader}
     * @memberof HBPathHeaderPatch
     */
    header: PathHeader;
    /**
     * 
     * @type {Patch}
     * @memberof HBPathHeaderPatch
     */
    body: Patch;
}

export function HBPathHeaderPatchFromJSON(json: any): HBPathHeaderPatch {
    return HBPathHeaderPatchFromJSONTyped(json, false);
}

export function HBPathHeaderPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBPathHeaderPatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': PathHeaderFromJSON(json['header']),
        'body': PatchFromJSON(json['body']),
    };
}

export function HBPathHeaderPatchToJSON(value?: HBPathHeaderPatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': PathHeaderToJSON(value.header),
        'body': PatchToJSON(value.body),
    };
}

