/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IfMatch
 */
export interface IfMatch {
}

export function IfMatchFromJSON(json: any): IfMatch {
    return IfMatchFromJSONTyped(json, false);
}

export function IfMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): IfMatch {
    return json;
}

export function IfMatchToJSON(value?: IfMatch | null): any {
    return value;
}

