/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchCreate
 */
export interface PatchCreate {
    /**
     * 
     * @type {number}
     * @memberof PatchCreate
     */
    parent_id: number;
    /**
     * 
     * @type {number}
     * @memberof PatchCreate
     */
    user_id: number;
    /**
     * 
     * @type {string}
     * @memberof PatchCreate
     */
    patch: string;
}

export function PatchCreateFromJSON(json: any): PatchCreate {
    return PatchCreateFromJSONTyped(json, false);
}

export function PatchCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parent_id': json['parent_id'],
        'user_id': json['user_id'],
        'patch': json['patch'],
    };
}

export function PatchCreateToJSON(value?: PatchCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent_id': value.parent_id,
        'user_id': value.user_id,
        'patch': value.patch,
    };
}

