/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PathHeader
 */
export interface PathHeader {
    /**
     * 
     * @type {string}
     * @memberof PathHeader
     */
    path: string;
}

export function PathHeaderFromJSON(json: any): PathHeader {
    return PathHeaderFromJSONTyped(json, false);
}

export function PathHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PathHeader {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'path': json['path'],
    };
}

export function PathHeaderToJSON(value?: PathHeader | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
    };
}

