/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EtagPathHeader
 */
export interface EtagPathHeader {
    /**
     * 
     * @type {number}
     * @memberof EtagPathHeader
     */
    etag: number;
    /**
     * 
     * @type {string}
     * @memberof EtagPathHeader
     */
    path: string;
}

export function EtagPathHeaderFromJSON(json: any): EtagPathHeader {
    return EtagPathHeaderFromJSONTyped(json, false);
}

export function EtagPathHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): EtagPathHeader {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'etag': json['etag'],
        'path': json['path'],
    };
}

export function EtagPathHeaderToJSON(value?: EtagPathHeader | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'etag': value.etag,
        'path': value.path,
    };
}

