/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Patch,
    PatchFromJSON,
    PatchFromJSONTyped,
    PatchToJSON,
} from './Patch';

/**
 * 
 * @export
 * @interface HBEmptyHeaderPatch
 */
export interface HBEmptyHeaderPatch {
    /**
     * 
     * @type {object}
     * @memberof HBEmptyHeaderPatch
     */
    header: object;
    /**
     * 
     * @type {Patch}
     * @memberof HBEmptyHeaderPatch
     */
    body: Patch;
}

export function HBEmptyHeaderPatchFromJSON(json: any): HBEmptyHeaderPatch {
    return HBEmptyHeaderPatchFromJSONTyped(json, false);
}

export function HBEmptyHeaderPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBEmptyHeaderPatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': json['header'],
        'body': PatchFromJSON(json['body']),
    };
}

export function HBEmptyHeaderPatchToJSON(value?: HBEmptyHeaderPatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': value.header,
        'body': PatchToJSON(value.body),
    };
}

