/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface HBEmptyHeaderListApiSchemasUser
 */
export interface HBEmptyHeaderListApiSchemasUser {
    /**
     * 
     * @type {object}
     * @memberof HBEmptyHeaderListApiSchemasUser
     */
    header: object;
    /**
     * 
     * @type {Array<User>}
     * @memberof HBEmptyHeaderListApiSchemasUser
     */
    body: Array<User>;
}

export function HBEmptyHeaderListApiSchemasUserFromJSON(json: any): HBEmptyHeaderListApiSchemasUser {
    return HBEmptyHeaderListApiSchemasUserFromJSONTyped(json, false);
}

export function HBEmptyHeaderListApiSchemasUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBEmptyHeaderListApiSchemasUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': json['header'],
        'body': ((json['body'] as Array<any>).map(UserFromJSON)),
    };
}

export function HBEmptyHeaderListApiSchemasUserToJSON(value?: HBEmptyHeaderListApiSchemasUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': value.header,
        'body': ((value.body as Array<any>).map(UserToJSON)),
    };
}

