/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HBEmptyHeaderUserCreate
 */
export interface HBEmptyHeaderUserCreate {
    /**
     * 
     * @type {object}
     * @memberof HBEmptyHeaderUserCreate
     */
    header: object;
    /**
     * 
     * @type {object}
     * @memberof HBEmptyHeaderUserCreate
     */
    body: object;
}

export function HBEmptyHeaderUserCreateFromJSON(json: any): HBEmptyHeaderUserCreate {
    return HBEmptyHeaderUserCreateFromJSONTyped(json, false);
}

export function HBEmptyHeaderUserCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBEmptyHeaderUserCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': json['header'],
        'body': json['body'],
    };
}

export function HBEmptyHeaderUserCreateToJSON(value?: HBEmptyHeaderUserCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': value.header,
        'body': value.body,
    };
}

