/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Patch,
    PatchFromJSON,
    PatchFromJSONTyped,
    PatchToJSON,
} from './Patch';

/**
 * 
 * @export
 * @interface HBEmptyHeaderListApiSchemasPatch
 */
export interface HBEmptyHeaderListApiSchemasPatch {
    /**
     * 
     * @type {object}
     * @memberof HBEmptyHeaderListApiSchemasPatch
     */
    header: object;
    /**
     * 
     * @type {Array<Patch>}
     * @memberof HBEmptyHeaderListApiSchemasPatch
     */
    body: Array<Patch>;
}

export function HBEmptyHeaderListApiSchemasPatchFromJSON(json: any): HBEmptyHeaderListApiSchemasPatch {
    return HBEmptyHeaderListApiSchemasPatchFromJSONTyped(json, false);
}

export function HBEmptyHeaderListApiSchemasPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBEmptyHeaderListApiSchemasPatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': json['header'],
        'body': ((json['body'] as Array<any>).map(PatchFromJSON)),
    };
}

export function HBEmptyHeaderListApiSchemasPatchToJSON(value?: HBEmptyHeaderListApiSchemasPatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': value.header,
        'body': ((value.body as Array<any>).map(PatchToJSON)),
    };
}

