/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PatchCreate,
    PatchCreateFromJSON,
    PatchCreateFromJSONTyped,
    PatchCreateToJSON,
} from './PatchCreate';

/**
 * 
 * @export
 * @interface HBEmptyHeaderPatchCreate
 */
export interface HBEmptyHeaderPatchCreate {
    /**
     * 
     * @type {object}
     * @memberof HBEmptyHeaderPatchCreate
     */
    header: object;
    /**
     * 
     * @type {PatchCreate}
     * @memberof HBEmptyHeaderPatchCreate
     */
    body: PatchCreate;
}

export function HBEmptyHeaderPatchCreateFromJSON(json: any): HBEmptyHeaderPatchCreate {
    return HBEmptyHeaderPatchCreateFromJSONTyped(json, false);
}

export function HBEmptyHeaderPatchCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBEmptyHeaderPatchCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': json['header'],
        'body': PatchCreateFromJSON(json['body']),
    };
}

export function HBEmptyHeaderPatchCreateToJSON(value?: HBEmptyHeaderPatchCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': value.header,
        'body': PatchCreateToJSON(value.body),
    };
}

