/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EtagPathHeader,
    EtagPathHeaderFromJSON,
    EtagPathHeaderFromJSONTyped,
    EtagPathHeaderToJSON,
} from './EtagPathHeader';
import {
    Patch,
    PatchFromJSON,
    PatchFromJSONTyped,
    PatchToJSON,
} from './Patch';

/**
 * 
 * @export
 * @interface HBEtagPathHeaderPatch
 */
export interface HBEtagPathHeaderPatch {
    /**
     * 
     * @type {EtagPathHeader}
     * @memberof HBEtagPathHeaderPatch
     */
    header: EtagPathHeader;
    /**
     * 
     * @type {Patch}
     * @memberof HBEtagPathHeaderPatch
     */
    body: Patch;
}

export function HBEtagPathHeaderPatchFromJSON(json: any): HBEtagPathHeaderPatch {
    return HBEtagPathHeaderPatchFromJSONTyped(json, false);
}

export function HBEtagPathHeaderPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBEtagPathHeaderPatch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': EtagPathHeaderFromJSON(json['header']),
        'body': PatchFromJSON(json['body']),
    };
}

export function HBEtagPathHeaderPatchToJSON(value?: HBEtagPathHeaderPatch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': EtagPathHeaderToJSON(value.header),
        'body': PatchToJSON(value.body),
    };
}

