/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Data,
    DataFromJSON,
    DataFromJSONTyped,
    DataToJSON,
} from './Data';
import {
    EtagPathHeader,
    EtagPathHeaderFromJSON,
    EtagPathHeaderFromJSONTyped,
    EtagPathHeaderToJSON,
} from './EtagPathHeader';

/**
 * 
 * @export
 * @interface HBEtagPathHeaderData
 */
export interface HBEtagPathHeaderData {
    /**
     * 
     * @type {EtagPathHeader}
     * @memberof HBEtagPathHeaderData
     */
    header: EtagPathHeader;
    /**
     * 
     * @type {Data}
     * @memberof HBEtagPathHeaderData
     */
    body: Data;
}

export function HBEtagPathHeaderDataFromJSON(json: any): HBEtagPathHeaderData {
    return HBEtagPathHeaderDataFromJSONTyped(json, false);
}

export function HBEtagPathHeaderDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBEtagPathHeaderData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': EtagPathHeaderFromJSON(json['header']),
        'body': DataFromJSON(json['body']),
    };
}

export function HBEtagPathHeaderDataToJSON(value?: HBEtagPathHeaderData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': EtagPathHeaderToJSON(value.header),
        'body': DataToJSON(value.body),
    };
}

