/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PathHeader,
    PathHeaderFromJSON,
    PathHeaderFromJSONTyped,
    PathHeaderToJSON,
} from './PathHeader';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface HBPathHeaderUser
 */
export interface HBPathHeaderUser {
    /**
     * 
     * @type {PathHeader}
     * @memberof HBPathHeaderUser
     */
    header: PathHeader;
    /**
     * 
     * @type {User}
     * @memberof HBPathHeaderUser
     */
    body: User;
}

export function HBPathHeaderUserFromJSON(json: any): HBPathHeaderUser {
    return HBPathHeaderUserFromJSONTyped(json, false);
}

export function HBPathHeaderUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBPathHeaderUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': PathHeaderFromJSON(json['header']),
        'body': UserFromJSON(json['body']),
    };
}

export function HBPathHeaderUserToJSON(value?: HBPathHeaderUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': PathHeaderToJSON(value.header),
        'body': UserToJSON(value.body),
    };
}

