/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Header,
    HeaderFromJSON,
    HeaderFromJSONTyped,
    HeaderToJSON,
} from './Header';
import {
    IntValue,
    IntValueFromJSON,
    IntValueFromJSONTyped,
    IntValueToJSON,
} from './IntValue';

/**
 * 
 * @export
 * @interface HBUnionIfMatchHeaderEmptyHeaderIntValue
 */
export interface HBUnionIfMatchHeaderEmptyHeaderIntValue {
    /**
     * 
     * @type {Header}
     * @memberof HBUnionIfMatchHeaderEmptyHeaderIntValue
     */
    header: Header;
    /**
     * 
     * @type {IntValue}
     * @memberof HBUnionIfMatchHeaderEmptyHeaderIntValue
     */
    body: IntValue;
}

export function HBUnionIfMatchHeaderEmptyHeaderIntValueFromJSON(json: any): HBUnionIfMatchHeaderEmptyHeaderIntValue {
    return HBUnionIfMatchHeaderEmptyHeaderIntValueFromJSONTyped(json, false);
}

export function HBUnionIfMatchHeaderEmptyHeaderIntValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): HBUnionIfMatchHeaderEmptyHeaderIntValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'header': HeaderFromJSON(json['header']),
        'body': IntValueFromJSON(json['body']),
    };
}

export function HBUnionIfMatchHeaderEmptyHeaderIntValueToJSON(value?: HBUnionIfMatchHeaderEmptyHeaderIntValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'header': HeaderToJSON(value.header),
        'body': IntValueToJSON(value.body),
    };
}

