/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IfMatchHeader,
    IfMatchHeaderFromJSON,
    IfMatchHeaderFromJSONTyped,
    IfMatchHeaderToJSON,
} from './IfMatchHeader';

/**
 * 
 * @export
 * @interface Header
 */
export interface Header {
    /**
     * 
     * @type {number}
     * @memberof Header
     */
    if_match: number;
}

export function HeaderFromJSON(json: any): Header {
    return HeaderFromJSONTyped(json, false);
}

export function HeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Header {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'if_match': json['if_match'],
    };
}

export function HeaderToJSON(value?: Header | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'if_match': value.if_match,
    };
}

