/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IfMatchHeader
 */
export interface IfMatchHeader {
    /**
     * 
     * @type {number}
     * @memberof IfMatchHeader
     */
    if_match: number;
}

export function IfMatchHeaderFromJSON(json: any): IfMatchHeader {
    return IfMatchHeaderFromJSONTyped(json, false);
}

export function IfMatchHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): IfMatchHeader {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'if_match': json['if_match'],
    };
}

export function IfMatchHeaderToJSON(value?: IfMatchHeader | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'if_match': value.if_match,
    };
}

