/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntValue
 */
export interface IntValue {
    /**
     * 
     * @type {number}
     * @memberof IntValue
     */
    value: number;
}

export function IntValueFromJSON(json: any): IntValue {
    return IntValueFromJSONTyped(json, false);
}

export function IntValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
    };
}

export function IntValueToJSON(value?: IntValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
    };
}

