/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Patch
 */
export interface Patch {
    /**
     * 
     * @type {number}
     * @memberof Patch
     */
    parent_id: number;
    /**
     * 
     * @type {number}
     * @memberof Patch
     */
    user_id: number;
    /**
     * 
     * @type {string}
     * @memberof Patch
     */
    patch: string;
    /**
     * 
     * @type {number}
     * @memberof Patch
     */
    id: number;
}

export function PatchFromJSON(json: any): Patch {
    return PatchFromJSONTyped(json, false);
}

export function PatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): Patch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parent_id': json['parent_id'],
        'user_id': json['user_id'],
        'patch': json['patch'],
        'id': json['id'],
    };
}

export function PatchToJSON(value?: Patch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent_id': value.parent_id,
        'user_id': value.user_id,
        'patch': value.patch,
        'id': value.id,
    };
}

